package rs.ac.bg.fon.nprog.forme.baletskagrupa;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import rs.ac.bg.fon.nprog.domen.ApstraktniDomenskiObjekat;
import rs.ac.bg.fon.nprog.domen.BaletskaGrupa;
import rs.ac.bg.fon.nprog.forme.OpstaEkranskaForma;
import rs.ac.bg.fon.nprog.kontroler.KontrolerKIPromeniPodatkeBaletskeGrupe;

public class FormaPromeniPodatkeBaletskeGrupe extends OpstaEkranskaForma {
    private final KontrolerKIPromeniPodatkeBaletskeGrupe kontroler;
    FormaPrikaziSveBaletskeGrupe formaSvi;

    /**
     * Creates new form FormaPromeniPodatkeBaletskeGrupe
     */
    public FormaPromeniPodatkeBaletskeGrupe(FormaPrikaziSveBaletskeGrupe forma,BaletskaGrupa baletskaGrupa) {
        initComponents();
        kontroler=new KontrolerKIPromeniPodatkeBaletskeGrupe(this, baletskaGrupa);
        this.formaSvi=forma;
        kontroler.popuniTipGrupe();
        kontroler.popuniKoreografe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBaletskaGrupaId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNazivGrupe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbTipGrupe = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtKapacitet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbKoreograf = new javax.swing.JComboBox();
        btnIzmeni = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDatumNastanka = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci baletske grupe"));

        jLabel1.setText("ID:");

        txtBaletskaGrupaId.setEditable(false);

        jLabel2.setText("Naziv grupe:");

        jLabel3.setText("Tip grupe:");

        jLabel4.setText("Kapacitet:");

        jLabel5.setText("Koreograf:");

        btnIzmeni.setText("Sačuvaj izmene");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel6.setText("Datum nastanka:");

        txtDatumNastanka.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIzmeni)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBaletskaGrupaId)
                            .addComponent(txtNazivGrupe, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(cmbTipGrupe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKapacitet)
                            .addComponent(cmbKoreograf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatumNastanka, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBaletskaGrupaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDatumNastanka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKoreograf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (txtNazivGrupe.getText().isEmpty() || txtKapacitet.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna!");
            return;
        }
        kontroler.SOPromeniBaletskuGrupu();
        formaSvi.azurirajTabelu((BaletskaGrupa) kontroler.getAdo());
    }                                         

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        kontroler.SOUcitajBaletskuGrupu();
    }                                 

    @Override
    public ApstraktniDomenskiObjekat kreirajObjekat() {
        return new BaletskaGrupa();
    }
    
    /**
     * @param args the command line arguments
     */

    public JComboBox getCmbKoreograf() {
        return cmbKoreograf;
    }

    public void setCmbKoreograf(JComboBox cmbKoreograf) {
        this.cmbKoreograf = cmbKoreograf;
    }

    public JComboBox getCmbTipGrupe() {
        return cmbTipGrupe;
    }

    public void setCmbTipGrupe(JComboBox cmbTipGrupe) {
        this.cmbTipGrupe = cmbTipGrupe;
    }

    public JTextField getTxtBaletskaGrupaId() {
        return txtBaletskaGrupaId;
    }

    public void setTxtBaletskaGrupaId(JTextField txtBaletskaGrupaId) {
        this.txtBaletskaGrupaId = txtBaletskaGrupaId;
    }

    public JTextField getTxtKapacitet() {
        return txtKapacitet;
    }

    public void setTxtKapacitet(JTextField txtKapacitet) {
        this.txtKapacitet = txtKapacitet;
    }

    public JTextField getTxtNazivGrupe() {
        return txtNazivGrupe;
    }

    public void setTxtNazivGrupe(JTextField txtNazivGrupe) {
        this.txtNazivGrupe = txtNazivGrupe;
    }

    public JTextField getTxtDatumNastanka() {
        return txtDatumNastanka;
    }

    public void setTxtDatumNastanka(JTextField txtDatumNastanka) {
        this.txtDatumNastanka = txtDatumNastanka;
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox cmbKoreograf;
    private javax.swing.JComboBox cmbTipGrupe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBaletskaGrupaId;
    private javax.swing.JTextField txtDatumNastanka;
    private javax.swing.JTextField txtKapacitet;
    private javax.swing.JTextField txtNazivGrupe;
    // End of variables declaration                   
}

